### ISSUE TITLE
Timeline not working properly in Safari

### ISSUE THREAD

**Issue by czhDavid** [lmc-eu/steward#140]
![bug](https://cloud.githubusercontent.com/assets/6987379/26121603/1e54ae8c-3a75-11e7-89f7-3a5139137f06.png)
On Safari the timeline is broken. Zooming or scrolling is not interacting with the items in the timeline. Athough the marking on top ( and the background grid) are zooming in and out as expected. 

In the console the error is following `[Error] Error: Invalid start "NaN"
	_applyRange (vis.min.js:30:29920)
	setRange (vis.min.js:30:29203)
	fit (vis.min.js:29:26181)
	(anonymous function) (vis.min.js:29:23945)
	emit (vis.min.js:28:13364)
	(anonymous function)
	_redraw (vis.min.js:31:26468)
	(anonymous function)
	(anonymous function) (vis.min.js:25:6846)`
and 
 `https://cdnjs.cloudflare.com/ajax/libs/vis/4.17.0/vis.map`

The version of safari is version 10.1 (12603.1.30.0.34)

**Comment by OndraM** [comment]
@czhDavid Thanks a lot for the report.

However as not having Safari myself, I'm tagging this "help wanted" for now - anyone (with Safari :-) ) is definitely welcome to dig in the issue.

**Comment by mijar** [comment]
Hi, I am also having this issue, the timeline does not work at all in Safari, no loaded items...using vis.js version 4.20.1, Safari v. 10.1.2. 
..would really appreciate if anyone could take a look at this :-)

**Comment by mijar** [comment]
...so after some debugging I have found out that the problem was caused in the initialization of data variable, where the start was set without format...
I checked [this question](https://stackoverflow.com/questions/21630125/date-issue-in-safari-ie) and firstly I tried to set it in the data var just with a static testing value off new Date(2017, 8, 8) which caused the timeline to work...so the next step was to find which way would work for our case. 
Hope this helps someone...

btw I also do not have Safari, I asked my colleague in Bali (7 hours time difference) to give me a remote access to her laptop and was checking all the stuff remotely :-)

**Comment by OndraM** [comment]
@mijar Hi, thanks a lot for all the findings! Aren't you interested in preparing a pull request to fix this issue in Safari :)?

**Comment by OndraM** [comment]
Ok, so should be fixed in #163. It will be part of next release. Thanks for the report and investigation 👍 .
