### ISSUE TITLE
bin/steward sets default time zone

### ISSUE THREAD

**Issue by gauthierm** [lmc-eu/steward#183]
The CLI wrapper script hard-codes the time zone to Europe/Prague. This can be handled by setting the default time zone in a setup step for tests but is not documented or expected.

**Comment by OndraM** [comment]
Hi @gauthierm, thanks for the report.

You are right and I will remove the whole `date_default_timezone_set` call, because starting with PHP 7 even not-set default timezone won't trigger the notoriously known warning ("You are *required* to use the date.timezone setting or the date_default_timezone_set() function.")

http://php.net/manual/en/migration70.other-changes.php#migration70.other-changes.remove-date-timezone-warning

However note this change will only be part of Steward master branch (which will undergo rapid backward incompatible changes soon), so for now I suggest using the workaround you mentioned.
