### ISSUE TITLE
Main difference from Codeception

### ISSUE THREAD

**Issue by drupalmk** [lmc-eu/steward#201]
Hi @OndraM 

I'm evaluating Steward as tests platform for my company.I'm looking for some points against Codeception.Have you done such comparison it in the past and can you provide me some most important difference and reasons that custom solution was created? Any feedback welcome. Cheers!

**Comment by OndraM** [comment]
Hi @drupalmk, thanks for you interest :).

Codeception is another great tool for testing, however, there are some fundamental differences.

- Both of the tools are built on top of PHPUnit, however, Steward directly runs PHPUnit testcases with only thin layer above them. Codeception adds its own domain syntax, inspired by behavior driven development (BDD). So in Steward, you write tests using "classic" phpUnit syntax, validate outcomes using classic assert methods etc., while in Codeception you use `AcceptanceTester $I` object and interact with it. 
- Codeception calls itself "full stack testing framework", because is made to be used for all layers of automated tests (unit tests, integration tests, API tests and finally end-to-end (alias functional) tests with Selenium). Steward is not a "testing framework" - it directly uses PHPUnit, and is focused purely on execution of end-to-end tests (written in PHPUnit format) and simplifies the overhead with browser setup etc. And if you want to write and run unit-tests, you will use PHPUnit directly (because for unit tests there is no need for Steward). 
- As Steward is specialized on executing end-to-end tests, which usually takes longer to execute, it executes tests in a parallel by default. This is a huge benefit if you are able to run multiple browser instances simultaneously - Steward will then via Selenium server execute multiple of your tests at the same time, vastly lowering the total execution time of your test suite. I believe there is some not-that-straightforward way how to achieve parallel execution in Codeception as well, but Codeception does not provide paralel execution by default.
- Another thing Steward can handle thanks to its focus on functional testing is "delay" between tests. While this is generally bad practice and you do not want to not time (or any) dependency between testscases, there are edge cases (like indexing item in fulltext engine which may take a minute or two, background message queue processing etc.) where you need to wait a while to be able to validate the whole scenario succeeded. Steward provide [simple way](https://github.com/lmc-eu/steward/wiki/Test-dependencies) how to achieve this, and also does some calculations to run dependent tests as the first (so meanwhile some tests with delay are waiting, other tests are being executed), also to lower the total execution time.

The reason why Steward was created (and also the reason why someone may choose it instead of Codeception) is that we are used to write unit tests in pure PHPUnit, we have like thousands of unit tests written in PHPUnit. We like the format (which is also familiar for people with eg. Java background, because PHPUnit itself is inspired by jUnit/TestNG), are experienced with it and we wanted to write functional tests using the same format. Ie. to not have different syntax for unit tests and different for functional tests. Also the parallelization and time-delay between testcases are features we didn't find in other testing tool usable for functional Selenium tests.

But if you like the BDD-inspired syntax of Codeception (which may be more readable for people without programming experience), and/or you want to use it for all layer of your tests, you won't make a mistake with Codeception.

If you have any other question, feel free to ask :).

**Comment by drupalmk** [comment]
@OndraM thanks a lot for a feedback!
