### ISSUE TITLE
Trying to get Steward working with headless

### ISSUE THREAD

**Issue by ShabariRepo** [lmc-eu/steward#233]
Hi all,

This may just be a quick inquiry but im trying to get headless working with steward simple test.  Im sure im just missing something stupid

Scenarios:
1. Non steward tests using just phpunit works with headless
`./vendor/phpunit/phpunit/phpunit --verbose -c ./TestAch.xml`

**Test Setup**
```
public function setUp()
    {
        $options = new ChromeOptions();
        
        $desired_capabilities = new DesiredCapabilities();
        $desired_capabilities->setBrowserName('chrome');
        $caps = DesiredCapabilities::chrome();

        $options->addArguments(['--headless', '--window-size=1920,1080', '--start-maximized']);
        $desired_capabilities->setCapability(ChromeOptions::CAPABILITY, $options);

        $caps->setCapability(ChromeOptions::CAPABILITY, $options);

        $capabilities = DesiredCapabilities::chrome();

        $this->_webdriver = RemoteWebDriver::create(
            'http://localhost:4444/wd/hub',
            $caps
        );
    }
```

2. Steward tests with passed params (capabilities) doesnt open in headless (opens browser)
`./vendor/bin/steward run staging chrome --capability "'chromeOptions':'args':['--headless', 'window-size=1024,768', '--no-sandbox']"`

**Comment by OndraM** [comment]
Hi, you cannot change desired capabilities inside the test (neither in the setUp method), because the moment tests begins, the browser is already opened.

For now, you'd need to create custom capabilities resolver, which would trigger the headless mode on startup. 
It should be quite easy though: see documentation here: https://github.com/lmc-eu/steward/wiki/Set-custom-capabilities#implement-custom-capabilities-resolver
And we are doing exactly this (starting chrome headless mode) in our example project:
https://github.com/lmc-eu/steward-example/blob/feature/next/src/CustomCapabilitiesResolver.php#L51

However I will create issue to think about easier way how to do this in futures.
