### ISSUE TITLE
Reuse loaded page in subsequent test

### ISSUE THREAD

**Issue by arnegroskurth** [lmc-eu/steward#236]
Is there a way to recycle the currently loaded page by a dependent test?

This would allow me to:
- test post-conditions on some interaction in a seperate test
- decrease test-time as I can avoid going through a complex click-path just to get to the same state that the last test already has been at

**Comment by OndraM** [comment]
Hi,
no there is no such option. But this is by design and also on purpose -
depending on browser state in subsequent test may lead to unexpected and
hard to debug scenarios.

While I understand your point, I believe this is not worth it: starting
with clean browser each time makes the tests much more predictable.

There is some other possibly when eg. your login workflow done on beginning
of each test is long: you can get PHP session ID cookie, store its value
using Steward Legacy component and restore it on beginning of some other
test. But this has it's downsides as well - you now don't depend on browser
state but on session state. And you usually want to avoid both of these
cases.

**Comment by arnegroskurth** [comment]
Hi @OndraM,

sure - I get that this can have nasty side-effects which should be avoided by-design as much as possible.

But maybe it makes sense to enforce a new browser instance only for every test case (class) instead of every test (method) within a test case. Within a test case it could still be the default to use a fresh instance but it could be made configurable via some annotation `@reuseInstance` or something similar which is valid in combination with `@depends`.

That would at lease solve it for my case.
